version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - npm install -g aws-cdk
      - cdk --version
      - python3 -m venv .env
      - chmod +x .env/bin/activate
      - . .env/bin/activate
      - pip3 install -r requirements.txt
  pre_build:
    commands:
      - ACCOUNT=675115824335
  build:
    commands:
      - cdk deploy -c account= -c environmentType=qa --require-approval never
